language: java
jdk:
- oraclejdk8
install: true
script:
- gradle zipMap
before_deploy:
- git config --global user.email "tripleabuilderbot@gmail.com" 
- git config --global user.name "tripleabuilderbot"
- export MAP_TAGGED_VERSION="$MAP_VERSION.$TRAVIS_BUILD_NUMBER"
- git tag $MAP_TAGGED_VERSION -a -m "$MAP_TAGGED_VERSION"
- git push -q https://$GITHUB_PERSONAL_ACCESS_TOKEN_FOR_TRAVIS@github.com/triplea-maps/$REPO_NAME --tags
deploy:
  provider: releases
  api_key:
    secure: 1ndVVmW1kpzWQPeDRT7/bzHl5ke5d1yrfzoaDr0naOUSdpAUQCSjo3FL3kvIAUwMq+UIYwgSf/jWA2lRqLUDnDxT7iOpTda41yG4xrZ2diRaXfiW3+J7qJEuTIufJrVQnMp1nv0pDJiWltV759ZqkUd9bYBwgyL2Cr/Ag0kelsWD2D22ZzrOzeK+Hgs+VGHbA8NvaNE6c4++AURwiaNYnXCOTHylUJWVx//q7uV+2KiDaVASwhYLTOGD+XleAQAipF0+LApCPI+ooXqEvXgM04oiLj/f1+kJV/fTSbKek8thJZ4IBHT5yZpGzpf1boE4apRGQk4bA9oGyQVRD+tmvt5ByzAFn8cV0jNPCanUZFbT40v9QvFHXfaW+uyQFX9gDiDS0gwegOMI5nz3kgJ0eazAnC3JssNwUSiZi2G40vHs3mp4RO4WfQPntXxKFupHg/PkpO90Zsvvgs7tqKD/RGOiwPAYoaub8CnvJFZGMjLJlVYo7Gintg/JbWEnD0ZUFwH2nmCP/XvxkwVatqgDdId/Su1dm8/30pVqH+s3m/KYqqicUiuWqINJg3EmAlbx15h7AUxw8E/iX2HVQ93AiEIo3yQGWccMNf8wdo2Ni+vvojNdQI7VJ6T9IWDW/kXMgi11vaQg3ffPSU/EQW2QHy8Y9TdPPYCdECqrqRQMTto=
  file: "$REPO_NAME.zip"
  skip_cleanup: true
  prerelease: true
  on:
    tags: false
    all_branches: true
